### ISSUE TITLE
[QUESTION] 1.18 ETA

### ISSUE THREAD

**Issue by latsdev** [HughBone/fabrilous-updater#11]
As I can't find any info regarding the 1.18 update for the mod, is there any ETA for 1.18 mod update?

**Comment by jschenke488** [comment]
The mod is already updated, but it hasn't been uploaded to CurseForge

**Comment by CivetKitty** [comment]
Anyone knows why it hasn't been uploaded yet? Preferrably, I want a direct response from Hughbone.

**Comment by HughBone** [comment]
I've been busy for the last few weeks, but will start updating soon.
