### ISSUE TITLE
Mods for Forge in update list while using Fabric

### ISSUE THREAD

**Issue by Taldariner** [HughBone/fabrilous-updater#2]
I have Adorn 1.14.1 for Fabric already installed, while Fabrilous Updater continues to offer me same version but for Forge, as it was uploaded to Modrinth later.

![image](https://user-images.githubusercontent.com/71024372/121766995-4599be00-cb5e-11eb-812e-51e7114ea92a.png)

![image](https://user-images.githubusercontent.com/71024372/121766923-e3d95400-cb5d-11eb-809f-271b898cbca5.png)

![image](https://user-images.githubusercontent.com/71024372/121766986-3155c100-cb5e-11eb-87cb-65c6cd20669c.png)

**Comment by HughBone** [comment]
this is sus
