### ISSUE TITLE
Fabrilous attempts to update fabric api 1.17 to 1.18, causing multiple errors

### ISSUE THREAD

**Issue by SylveonBottle** [HughBone/fabrilous-updater#8]
Currently using `fabric-api-0.40.1+1.17`
When using `/fabdate update`, Fabrilous Updater points to a new fabric version at:
https://cdn.modrinth.com//data/P7dR8mSH/versions/0.40.1+1.18_experimental/fabric-api-0.40.1+1.18_experimental.jar

**Comment by HughBone** [comment]
Duplicate of Issue #4
